using DG.Tweening;
using System;
using System.Collections;
using UnityEngine;
using UnityEngine.SceneManagement;
using UnityEngine.UI;

public class SceneChanger : MonoBehaviour
{
    #region  인스턴스 등록
    public static SceneChanger Instance
    {
        get
        {
            return instance;
        }
    }
    private static SceneChanger instance;
    #endregion

    #region 변수
    [SerializeField]
    CanvasGroup Fade_img;
    [SerializeField]
    float fadeDuration = 2;
    [SerializeField]
    GameObject Loading;
    [SerializeField]
    Text Loading_text;

    AudioSource[] AllAudio;

    public Action TutorialAction;
    #endregion
    void Awake()
    {
        if (instance != null)
        {
            DestroyImmediate(this.gameObject);
            return;
        }
        instance = this;

        DontDestroyOnLoad(gameObject);

        SceneManager.sceneLoaded += OnSceneLoaded;
    }

    private void OnDestroy()
    {
        SceneManager.sceneLoaded -= OnSceneLoaded;
    }


    public void ChangeScene(String sceneName)
    {
        Fade_img.DOFade(1, fadeDuration)
        .OnStart(() => {
            Fade_img.blocksRaycasts = true;
        })
        .OnComplete(() => {
            DOTween.CompleteAll();
            DOTween.KillAll();
            StopAllCoroutines();
            StartCoroutine("LoadScene", sceneName);
        });
    }

    IEnumerator LoadScene(string sceneName)
    {
        Loading.SetActive(true);

        AllAudio = FindObjectsOfType<AudioSource>(); 
        foreach(AudioSource audio in AllAudio){audio.Stop();}

        AsyncOperation async = SceneManager.LoadSceneAsync(sceneName);
        async.allowSceneActivation = false; 

        float past_time = 0;
        float percentage = 0;

        while (!(async.isDone))
        {
            yield return null;

            past_time += Time.deltaTime;

            if (percentage >= 90)
            {
                percentage = Mathf.Lerp(percentage, 100, past_time);

                if (percentage == 100)
                {
                    async.allowSceneActivation = true;
                    if(TutorialAction != null) TutorialAction?.Invoke(); //HJ_로딩끝나면 튜토리얼 재생하는 이벤트 실행
                }
            }
            else
            {
                percentage = Mathf.Lerp(percentage, async.progress * 100f, past_time);
                if (percentage >= 90) past_time = 0;
            }
            Loading_text.text = percentage.ToString("0") + "%"; 
        }
    }


    private void OnSceneLoaded(Scene scene, LoadSceneMode mode)
    {
        Fade_img.DOFade(0, fadeDuration)
        .OnStart(() => {
            Loading.SetActive(false);
        })
        .OnComplete(() => {
            Fade_img.blocksRaycasts = false;
        });
    }

}
